## UniFlex Agent config file

config:
  name: 'Local_IPerf_Controller'
  info: 'Local UniFlex control program testing iperf app'
  iface: 'lo'

control_applications:
  myController:
      file : local_control_app.py
      class_name : MyIperfController
      kwargs : {}

  iperf:
      module : uniflex_app_iperf
      class_name : IperfModule
      kwargs : {}
