## WiSHFUL Agent config file

config:
  name: 'local_wifi_device'
  info: 'Just local device without control logic'
  type: 'slave'
  iface: 'eth0'
  sub: "tcp://192.168.200.14:8990"
  pub: "tcp://192.168.200.14:8989"

modules:
  wifi:
      module : uniflex_module_wifi_ath
      class_name : AthModule
      devices : ['phy1']
