## UniFlex Agent config file

agent_config:
  name: 'local_AP_control_progs'
  info: 'Control programs running on each AP locally'
  type: 'local'
  iface: 'lo'

controllers:
  scanner:
      file : ap_control_programs.py
      class_name : Scanner
      kwargs : {"mode": "LOCAL", "ap_iface": "ap1", "scan_iface": "lo", "channels": [44, 48], "hopping_interval": 1, "reporting_interval":1}

modules:
  discovery:
      module : uniflex_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"lo", "groupName":"uniflex_1234"}

  wifi:
      module : uniflex_module_wifi
      class_name : WifiModule
      devices : ['phy0']
