## UniFlex Agent config file

agent_info:
  name: 'agent_123'
  info: 'agent_info'
  iface: 'eth0'

modules:
  discovery:
      module : uniflex_module_discovery_pyre
      class_name : PyreDiscoverySlaveModule
      kwargs: {"iface":"eth0", "groupName":"uniflex_1234"}

  simple:
      module : uniflex_module_spectral_scan_ath9k
      class_name : SpectralScanAth9kModule
      interfaces : ['wlan0']

  iperf:
      module : uniflex_module_iperf
      class_name : IperfModule

##  rule_manager:
##      module : uniflex_module_rules
##      class_name : RuleManagerModule
