## UniFlex Controller's config file

controller:
    name: "Controller"
    info: "UniFlex Controller"
    dl: "tcp://192.168.1.157:8990"
    ul: "tcp://192.168.1.157:8989"

modules:
    discovery:
        module : uniflex_module_discovery_pyre
        class_name : PyreDiscoveryMasterModule
        kwargs: {"iface":"em0", "groupName":"uniflex_1234", "downlink":"tcp://192.168.1.157:8990", "uplink":"tcp://192.168.1.157:8989"}
