## UniFlex Agent config file

agent_config:
  name: 'HC node'
  info: 'filter runs on local node'
  iface: 'lo'

controllers:
  myFilter:
      file : my_filter.py
      class_name : MyAvgFilter
      kwargs : {"window": 5}

modules:
  discovery:
      module : uniflex_app_discovery_pyre
      class_name : PyreDiscoverySlaveModule
      kwargs: {"iface":"lo", "groupName":"uniflex_1234"}

  simple:
      module : uniflex_module_simple
      class_name : SimpleModule2
      mode : local # able to communicate only with local apps; by default global
      devices : ['phy0']

  iperf:
      module : uniflex_module_iperf
      class_name : IperfModule
