## UniFlex Agent config file

agent_config:
  name: 'local_AP_control_progs'
  info: 'Local WiFi agent'
  type: 'slave'
  iface: 'lo'

modules:
  discovery:
      module : uniflex_module_discovery_pyre
      class_name : PyreDiscoverySlaveModule
      kwargs: {"iface":"lo", "groupName":"uniflex_1234"}

  simple_radio:
      module : uniflex_module_simple
      class_name : SimpleModule2
      devices : ['phy0']

  simple_net:
      module : uniflex_module_simple
      class_name : SimpleModule3
