## UniFlex Agent config file

config:
  name: 'HC node'
  info: 'filter runs on local node'
  iface: 'lo'

control_applications:
  myFilter:
      file : my_filter.py
      class_name : MyAvgFilter
      kwargs : {"window": 50}

modules:
  discovery:
      module : uniflex_module_discovery_pyre
      class_name : PyreDiscoverySlaveModule
      kwargs: {"iface":"lo", "groupName":"uniflex_1234"}

  wifi:
      module : uniflex_module_wifi
      class_name : WifiModule
      devices : ['phy0']
