## UniFlex Agent config file

agent_config:
  name: 'HC node'
  info: 'filter runs on local node'
  type: 'slave'
  iface: 'lo'

controllers:
  myFilter:
      file : my_filter.py
      class_name : MyAvgFilter
      kwargs : {"window": 50}

modules:
  discovery:
      module : uniflex_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"lo", "groupName":"uniflex_1234"}

  wifi:
      module : uniflex_module_wifi
      class_name : WifiModule
      devices : ['phy0']
