## UniFlex Agent config file
url: 

config:
  name: "Backbone Network Controller"
  info: "Backbone Network Controller"
  iface: 'wlp2s0'
  sub: "tcp://100.0.0.2:8990"
  pub: "tcp://100.0.0.2:8989"

broker:
  xpub: "tcp://100.0.0.2:8990"
  xsub: "tcp://100.0.0.2:8989"

control_applications:
  myController:
      file : my_control_app.py
      class_name : MyController
      kwargs : {}
